# Generated by Django 4.0 on 2021-12-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpModel',
        ),
    ]
