# Generated by Django 4.0 on 2022-02-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='-', max_length=100)),
                ('last_name', models.CharField(default='-', max_length=100)),
                ('phone', models.CharField(default='-', max_length=15)),
                ('email', models.EmailField(default='-', max_length=254)),
                ('street', models.CharField(default='-', max_length=100)),
                ('house_num', models.CharField(default='-', max_length=100)),
                ('postal_code', models.CharField(default='-', max_length=100)),
                ('postal_city', models.CharField(default='-', max_length=100)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(default='-', max_length=100)),
                ('farm_id_num', models.CharField(default='-', max_length=100)),
                ('farm_type', models.CharField(blank=True, choices=[('1', 'Uprawy polowe'), ('2', 'Uprawy ogrodnicze'), ('3', 'Uprawy trwałe'), ('4', 'Krowy mleczne'), ('5', 'Zwierzęta trawożerne'), ('6', 'Trzoda chlewna'), ('7', 'Drób'), ('8', 'Mieszane')], max_length=1, null=True)),
                ('farmers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.farmer')),
            ],
            options={
                'ordering': ['farm_name'],
            },
        ),
    ]
